services:
  - type: web
    name: matka-api-server
    env: node
    plan: free
    runtime: node-20
    region: oregon
    buildCommand: "bash build.sh"
    startCommand: "cd artifacts/api-server && node dist/index.js"
    healthCheckPath: /api/healthz
    healthCheckInterval: 300
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "4000"
      - key: DATABASE_URL
        sync: false
      - key: APP_URL
        value: https://matka-api-server.onrender.com
      - key: JWT_SECRET
        sync: false
      - key: PNPM_HOME
        value: /opt/render/.pnpm
      - key: NPM_CONFIG_REGISTRY
        value: https://registry.npmjs.org/
