import { Router, type IRouter } from "express";
import healthRouter from "./health.js";
import authRouter from "./auth.js";
import setupRouter from "./setup.js";
import dashboardRouter from "./dashboard.js";
import usersRouter from "./users.js";
import marketsRouter from "./markets.js";
import markets2Router from "./markets2.js";
import resultsRouter from "./results.js";
import bidsRouter from "./bids.js";
import bids2Router from "./bids2.js";
import depositsRouter from "./deposits.js";
import withdrawalsRouter from "./withdrawals.js";
import gameRatesRouter from "./game-rates.js";
import noticesRouter from "./notices.js";
import settingsRouter from "./settings.js";
import scraperRouter from "./scraper.js";
import scraper2Router from "./scraper2.js";
import userRouter from "./user.js";
import upiMethodsRouter from "./upi-methods.js";
import apkFilesRouter from "./apk-files.js";
import notificationsRouter from "./notifications.js";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(setupRouter);
router.use(dashboardRouter);
router.use(usersRouter);
router.use(marketsRouter);
router.use(markets2Router);
router.use(resultsRouter);
router.use(bidsRouter);
router.use(bids2Router);
router.use(depositsRouter);
router.use(withdrawalsRouter);
router.use(gameRatesRouter);
router.use(noticesRouter);
router.use(settingsRouter);
router.use(scraperRouter);
router.use(scraper2Router);
router.use(userRouter);
router.use(upiMethodsRouter);
router.use(apkFilesRouter);
router.use(notificationsRouter);

export default router;
